---
title: "Command output"
format: html
---

```{=html}
<script src="https://kit.fontawesome.com/ece750edd7.js" crossorigin="anonymous"></script>
```

## Redirecting output to file

So far, most of our command outputs have been printed to screen without saving the results or doing anything with the results. Here we will look at how to direct our outputs into a file.

To write the results of a command into a file, we can redirect the output with the `>` symbol. Rather than printing results to the terminal, this symbol will write to the filename given after the `>` symbol.

For example, let's create a file named `my_commands.txt` that contains the text "My commands:", followed by our command history.

We first need to add the line "My commands:" to a new file. This can be done using the `echo` command, which simply prints out the text that you give it. 

``` bash
echo "My commands:"
```

If instead, we redirect the output to a file then the text will be saved. 

``` bash
echo "My commands:" > my_commands.txt
```

:::: challenge
<h2><i class="fas fa-pencil-alt"></i> Challenge 1:</h2>

Check if the file has been created and contains the redirected output. 

<details>

<summary>Solution</summary>

::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

Remember that we can use a `cat` or `less` to take a look at the content of a file.

``` bash
cat my_commands.txt
```
:::

</details>
::::

Now that we have the header, we need to add the content of our command history. We can get our history using the `history` command. Using `>` we can redirect the output to our file. 

``` bash
history > my_commands.txt

head my_commands.txt
```

It seems that the file has been overwritten and the redirect has removed our original header. With redirects, Linux overwrites existing files without warning. Luckily, there is a way to append to an existing file without overwriting it, using `>>`.

``` bash
echo "My commands:" > my_commands.txt

history >> my_commands.txt

head my_commands.txt
```

Now, the original content has been kept and the history of commands has been added to the file. 

::: {.key-points}
<h2><i class="fas fa-thumbtack"></i> Key points</h2>

There are several different options to redirect output. 

- `>` redirects output, overwriting if a file exists
- `>>` redirects output and appends the results to an existing file
- `2>` will redirect errors only, overwriting if a file exists
- `2>>` will redirect errors only and adding errors to an existing file
- `2>&1` redirects errors to the standard output (useful if you want to record errors and outputs together)

:::

## Combining commands (pipes)

Some of the power of Linux comes from the ability to string commands together to form "pipelines".
Using the `|` pipe symbol, the output of one command can be used as the input for a second command. 

For example, if we want to count the number of lines in a gzipped file, this can be done by first using `zcat` to get the uncompressed content of the file and piping the output into `wc` to count the lines and characters within the file:

``` bash
cd ~/Intro_to_Linux/yeast_files/

zcat raw_yeast_rnaseq_data.fastq.gz | wc
```

If you simply run `wc` on the file, you will get a result, however it will be nonsense as `wc` doesn't know how to decompress the file before counting the content.

Let's say we want to find the first five lines in `raw_yeast_rnaseq_data.fastq.gz` that contains the sequence *ACTG*.

We could perform this in three separate commands and save the input as we go:

``` bash
## Save the uncompressed output
zcat raw_yeast_rnaseq_data.fastq.gz > raw_yeast_rnaseq_data.fastq

## Find all lines with ACTG
grep "ACTG" raw_yeast_rnaseq_data.fastq > ACTG_raw_yeast_rnaseq_data.txt

## Print the first five lines
head -n 5 ACTG_raw_yeast_rnaseq_data.txt

## Remove intermediate files
rm raw_yeast_rnaseq_data.fastq ACTG_raw_yeast_rnaseq_data.txt
```

Pipes are particularly as they remove the need to create these large intermediate files. They can also save time. In this example, there is no need to keep reading the input file once five instances of *ACTG* are found. When we pipe commands, all commands will terminate when the final command has completed. This can save considerable time with large files.

``` bash
zcat raw_yeast_rnaseq_data.fastq.gz | grep "ACTG" | head -n 5
```

## Exercises

Below are a number of exercises exploring files and redirection. 

:::: exercise
<h2><i class="fa fa-pencil-alt"></i> Exercise 1:</h2>

Go into the yeast_files folder. Save the first 20 lines of the `raw_yeast_rnaseq_data.fastq.gz` to a file named `header.txt`, without unpacking the gzipped file.

<details>
<summary>Solution</summary>
::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

The first thing we should do is extract the content of the gzipped file. With `zcat` we can print the whole file to the terminal, then pipe this into the `head` command to extract the first lines. Remember that we can change the number of lines we want with `-n`. And finally we can redirect the results into a file.  

``` bash
cd ~/Intro_to_Linux/yeast_files

zcat raw_yeast_rnaseq_data.fastq.gz | head -n 20 > header.txt
```
:::
</details>
::::

:::: exercise
<h2><i class="fa fa-pencil-alt"></i> Exercise 2:</h2>

Extract the lines starting with an `@` from the gzipped file. Print the last 10 lines to screen.

<details>
<summary>Solution</summary>
::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

We can search within a gzipped file using `zgrep`. To search for lines starting with an `@` we have to use the `^` symbol. Once we have these extracted, print the last 10 lines with `tail`. By default, it prints the last 10 lines.

``` bash
zgrep "^@" raw_yeast_rnaseq_data.fastq.gz | tail
```
:::
</details>
::::

:::: exercise
<h2><i class="fa fa-pencil-alt"></i> Exercise 3:</h2>

Extract the lines starting with an `@` from the gzipped file. Print the first and the last 10 lines to a file called `names.txt`.

NOTE: You can't do this in a single command. You will need to get the first 10 lines and last 10 lines separately and combine them in a single output file.

<details>
<summary>Solution</summary>
::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

We can use `>>` to append the output of our second command to the output of our first command.

``` bash
zgrep "^@" raw_yeast_rnaseq_data.fastq.gz | head > names.txt

zgrep "^@" raw_yeast_rnaseq_data.fastq.gz | tail >> names.txt
```
:::
</details>
::::
