---
title: "Bioinformatics 101"
format: html
---

```{=html}
<script src="https://kit.fontawesome.com/ece750edd7.js" crossorigin="anonymous"></script>
```

## File Types

Linux is often used to analyse large amounts of data. Whenever the data comes from a biological source, we call this type of analysis bioinformatics. There are a number of common files that are used in many different types of analysis. We have seen two of them so far, FASTQ and BED.

Many of the most common types of file that you will have to work with as a bioinformatician take the form of structured text files, examples include:

- Standard formats for representing raw sequences
  - [FASTA](https://en.wikipedia.org/wiki/FASTA_format)
  - [FASTQ](https://en.wikipedia.org/wiki/FASTQ_format)
- Tabular formats for representing aligned reads or genome features
  - [BED](https://en.wikipedia.org/wiki/BED_(file_format))
  - [GTF](https://en.wikipedia.org/wiki/Gene_transfer_format)
  - [SAM](https://en.wikipedia.org/wiki/SAM_(file_format))

These standard file formats have specific structures. This ensures that information is always recorded in the same way and provides compatibility with bioinformatics software and tools. 

## Tools

Today, we will look at a fairly typical bioinformatics task; aligning reads to an existing reference genome. To simplify things, the following choices about the analysis have been made:

1. We will skip any pre-processing of reads, even though they might contain adapter sequences or low quality data. 
2. **STAR** will be used for aligning reads, this is a very popular aligner for RNA-seq data. Many different tools are available, but most of the tools will produce **SAM** files as outputs. 
3. The **samtools** package will be used to view and summarise the resulting **SAM** files. Again other toolkits are available, however **samtools** is a very popular and commonly used tool. 
4. Finally, we will use **bedtools** to look at reads mapping to gene regions of the reference genome.

By default, these tools are not installed on Linux servers and have to be installed separately.

**Note:** This is not a full pipeline, we will provide examples of more thorough sequencing analyses in future workshops.

## Analysis

First, lets take a look at the data. We are going to align RNA-seq reads from *saccharomyces cerevisiae* to the yeast reference genome. The files are in the `yeast_files` directory.

``` bash
cd ~/Intro_to_Linux/yeast_files/
```

The reference genome sequence is stored in `yeast_genome.fasta`, while gene annotations and locations are recorded in `yeast_genes.bed`.

:::: challenge
<h2><i class="fas fa-pencil-alt"></i> Challenge 1:</h2>

Print the first 5 lines for each of the reference genome files.
<details>

<summary>Solution</summary>

::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

To get the first 5 lines of a file, we can use the `head` command. 

``` bash
head -n 5 yeast_genome.fasta

head -n 5 yeast_genes.bed
```
:::

</details>
::::

The first column of the BED file refers to the chromosome name, and in the FASTA file the name behind the `>` symbol refers to the name of the chromosome. As you can see, there is a discrepancy between the files and the names for the chromosome.

This is a common problem in bioinformatics, as data can come from different sources and use different naming conventions. We need to fix this problem before we move on. The easiest fix is to remove `chr` from the BED file. For this, the `sed` command can be used, which can replace patterns in a file with another piece of text. For example:

``` bash
sed "s/^chr//" yeast_genes.bed > yeast_genes_fixed.bed
```

Let's break down the sed command:

- `s` stands for search and replace
  - The pattern between the first two `/` is the text we want to search for 
  - The text between the second and third `/` is the replacement text
- Thus `s/^chr//` will find lines that begin with "chr" and remove these three characters.

The results are written to `yeast_genes_fixed.bed`. Note that `sed` does not edit the original file `yeast_genes.bed`. Inline editing is possible with `-i` option in sed.

To confirm the replacement has worked, lets run the `head` command again. 

``` bash
head -n 5 yeast_genes_fixed.bed
```

This only confirms it for the first few lines. To check throughout the file, we can pipe a few useful commands together. 

- `cut` can extract columns of data from a file
- `sort` provides classic character and numerical sort functionality
- `uniq` removes consecutive lines that are duplicated

``` bash
cut -f 1 yeast_genes_fixed.bed | sort | uniq
```

The command above will thus show us the unique values in the first column of `yeast_genes_fixed.bed`.

:::: challenge
<h2><i class="fas fa-pencil-alt"></i> Challenge 2:</h2>

See if you can produce a count for the number of genes per chromosome. 
*Hint: take a look at the `uniq` command, it has an option to count values*

<details>

<summary>Solution</summary>

::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

``` bash
uniq --help
```
The `uniq` command has an option `-c`. If we add that to the command, it should give us a count of the number of lines (genes) for each chromosome.

``` bash
cut -f 1 yeast_genes_fixed.bed | sort | uniq -c
```
:::

</details>
::::

Now that our genome annotation files are compatible, we can proceed with aligning RNA-seq reads to the reference. The first step is to index the genome. Indexing is used by mappers to make mapping faster and easier. Most alignment tools have the option to create an index. The command to create an index for `STAR` is below: 

``` bash
## Create a folder for the index
mkdir star_index

## Run STAR in genomeGenerate mode
STAR --runThreadN 5 --runMode genomeGenerate --genomeDir star_index --genomeFastaFiles yeast_genome.fasta --genomeSAindexNbases 10
```

The `--runThreadN` option tells STAR how many 'threads' or 'CPUs' to use. Many command line tools can run on multiple CPUs to speed up processing. However, you should be wary of hogging all of the compute power on a shared server. We will look into how to determine the number of threads later. 

The `--genomeSAindexNbases` option controls the size of the index created. You can read more about the various options available in the [STAR documentation](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf).

Once the index has been created, the reads can be mapped to the genome. The command requires paths to the raw reads and the index folder. 

``` bash
STAR --genomeDir star_index --readFilesIn raw_yeast_rnaseq_data.fastq.gz --runThreadN 2 --outFileNamePrefix raw_yeast_rnaseq_data. --outSAMtype BAM SortedByCoordinate --readFilesCommand 'gunzip -c' 
```

The `--readFilesCommand 'gunzip -c'` option instructs STAR to unzip the compressed fastq files.

The output is a `BAM` file, which is the binary version of a `SAM` file. It contains a lot of information about each read and its alignment to the genome. 

We can use `samtools flagstat` to check how many reads map to the reference genome.

``` bash
samtools flagstat raw_yeast_rnaseq_data.Aligned.sortedByCoord.out.bam
```

We can see that 100% of the reads map to the reference genome. Many of the reads have secondary locations, meaning that the read aligns to multiple locations on the genome. For RNA-seq data this is a normal occurrence.

The [bedtools]() package has many tools for performing operations on genomic data. We can use `genomecov` to convert a BAM file into a **bedgraph** file of sequencing coverage. The output **bedgraph** file shows the sum of sequencig reads overlapping each genomic base. 

``` bash
bedtools genomecov -ibam raw_yeast_rnaseq_data.Aligned.sortedByCoord.out.bam -bg > raw_yeast_rnaseq_data.genomecov.bg

head raw_yeast_rnaseq_data.genomecov.bg
```

We can use `intersect` to count the number of reads overlapping each gene in `yeast_genes_fixed.bed`.

``` bash
bedtools intersect -c -a yeast_genes_fixed.bed -b raw_yeast_rnaseq_data.Aligned.sortedByCoord.out.bam > raw_yeast_overlap_data.bed

head raw_yeast_overlap_data.bed
```

For each gene, the number of overlapping reads is recorded in the 7th column.

:::: challenge
<h2><i class="fas fa-pencil-alt"></i> Challenge 3:</h2>

What is the maximum amount of reads mapping to a gene? 
 
*Hint: Use the `cut` and `sort` commands, check the `--help` of `sort` to see how to sort numeric values.*

<details>

<summary>Solution</summary>

::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

Using `cut` we can extract the 7th column and then sort them by number.

``` bash
sort --help

cut -f 7 raw_yeast_overlap_data.bed | sort -n 
```

The maximum count is 3,730 reads.

:::

</details>
::::

:::: challenge
<h2><i class="fas fa-pencil-alt"></i> Challenge 4:</h2>

Can you find which gene has the highest read count?

*Hint: Use `grep`*

<details>

<summary>Solution</summary>

::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

Using `grep` we can extract the exact number.

``` bash
grep "3730" raw_yeast_overlap_data.bed
```

There are different lines that contain this number, but only one in the last column, which is for the gene "RDN37-2".

:::

</details>
::::

Alternatively, `sort` allows you to sort a file by specific columns.

``` bash
sort -k7,7nr raw_yeast_overlap_data.bed | head
```

We can break this down as follows:

- `-k7,7`: Sort using the column range 7,7 (We could use multiple columns)
- `-n`: Perform a numerical sort
- `-r`: Perform a reverse sort to output the results in descending order

## Threads

Now, as mentioned, many of the commands run within bioinformatics can run on multiple threads (also referred to as cpus). Every computer has them, but processes need to share them. Which mean that if we are working on a server, we need to make sure that the commands being run aren't claiming all the threads that are available. \
To check how many processes are currently running, there are two commands to use: 

- `top` shows all active processes
- `htop` gives a user friendly representation of the processes currently running along with CPU and memory usage on the server

:::: challenge
<h2><i class="fas fa-pencil-alt"></i> Challenge 5:</h2>

Using `htop`, can you see how many tasks are running?

<details>

<summary>Solution</summary>

::: solution
<h2><i class="far fa-eye"></i> Solution:</h2>

There should be a line which says how many tasks are currently running. The screen also shows how much memory is being used. 

:::

</details>
::::

Before running any process, it is good to check what the status of the system is. 

## AWK

Lastly, one powerful command line tool that can be very helpful, though somewhat complex, is `awk`. It can help analyse, filter or manipulate structured files. Lets look at an example to see if we can use `awk` to find the longest genes within our genome. Gene length isn't captured within the BED file, however the start and stop position are given. The follow command will give us the top 10 longest genes. 
 
``` bash
awk -F'\t' -v OFS='\t' '{print $4,$3-$2}' yeast_genes_fixed.bed | sort -k2,2nr | head
```

Lets break down the command, because this is complex. 

- `-F '\t'` sets what the separator is within the file. This is the character which is between the columns. `\t` as we saw at regular expressions means `tab`. 
- `-v OFS='\t'` tells `awk` that the output should be `tab` separated as well
- `'{print $4,$3-$2}'` is where the magic happens. `awk` processes every line of a file one by one. It separates the all the columns and renames them to `$1`, `$2`, etc to the last column index. This means we can make changes to the order, but also do calculations with the different columns. If we substract the start position of our gene from the stop position, it will give the gene length. What this means for this part of the command is that it will report the 4th column followed by the stop column minus the start column. 
- `sort -k2,2nr` will sort the resulting list. `-k2,2` specifies the list should be sorted by the second column, and `nr` specifies that the sort is numeric and should be sorted in the reverse order. 

If `awk` is of interest to you, take a look at [Effective AWK Programming](https://www.gnu.org/software/gawk/manual/). Don't worry if this looks extremely complex, this is an advanced Linux command that will become more useful as you get into more difficult challenges.  
