---
title: "Bioinformatics on the Linux command line"
format: html
---

```{=html}
<script src="https://kit.fontawesome.com/ece750edd7.js" crossorigin="anonymous"></script>
```

Welcome to our introductory Linux command line workshop. 

During this course you will learn to:

-   Connect to a server
-   Navigate the file system using the Linux command shell
-   Use basic shell commands to view and filter data
-   Perform basic analysis with bioinformatics tools

This course is hosted by the Bioinformatics Core at the [DRP-HCB](https://biology.ed.ac.uk/drp).

### Course Setup

If you are using the DRP-HCB Bioinformatics server for this course then all of the data and software is already installed. If you are working through this course from a different Linux computer or server, please make sure the following tools are installed:

::: resources
<h2><i class="fas fa-save"></i> Required software</h2>

- [nano](https://www.nano-editor.org/)
- [STAR](https://github.com/alexdobin/STAR)
- [samtools](https://www.htslib.org/)
- [bedtools](https://bedtools.readthedocs.io/en/stable/)

An easy way to install is through [conda](https://continuumio-docs.readthedocs-hosted.com/miniconda/). Check out [our guide](https://drp-hcb-bioinformatics.github.io/DRP-HCB-Bioinformatics/software.html) and explore how to install and work with conda. Tools can then be installed by downloading [the setup (yml) file](https://raw.githubusercontent.com/DRP-HCB-Bioinformatics/Bioinformatics_on_the_Linux_command_line/refs/heads/main/env/BotLcl.yml) and running the following commands to install and activate the environment. 

``` bash
wget https://raw.githubusercontent.com/DRP-HCB-Bioinformatics/Bioinformatics_on_the_Linux_command_line/refs/heads/main/env/BotLcl.yml

conda env create -f BotLcm.yml

conda activate BotLcm
``` 

